version = "3.11.5"
runner.dialect = scala3
maxColumn = 120
rewrite.rules = [SortImports]
rewrite.insertBraces.minLines = 1
rewrite.insertBraces.allBlocks = true
project.excludePaths = [
  "glob:**/benchmark/**",
  "glob:**/out/**",
  "glob:**/.scala-build/**",
  "glob:**/scalex-workspace/**",
  "glob:**/.local/**"
]
